# frozen_string_literal: true

source 'https://rubygems.org'

gem 'auth', github: 'alexfalkowski/auth', tag: 'v1.55.1', glob: 'test/*.gemspec'
gem 'cucumber'
gem 'nonnative'
gem 'rspec-expectations'
gem 'rspec-wait'
gem 'rubocop'
