// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: migrieren/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MigrationState identifies whether a database has no recorded migration,
// a clean recorded version, or a dirty recorded version.
type MigrationState int32

const (
	// MIGRATION_STATE_UNSPECIFIED is the default value for unknown states.
	MigrationState_MIGRATION_STATE_UNSPECIFIED MigrationState = 0
	// MIGRATION_STATE_UNAPPLIED means no migration version has been recorded.
	MigrationState_MIGRATION_STATE_UNAPPLIED MigrationState = 1
	// MIGRATION_STATE_CLEAN means a non-dirty migration version is recorded.
	MigrationState_MIGRATION_STATE_CLEAN MigrationState = 2
	// MIGRATION_STATE_DIRTY means the recorded migration version is dirty.
	MigrationState_MIGRATION_STATE_DIRTY MigrationState = 3
)

// Enum value maps for MigrationState.
var (
	MigrationState_name = map[int32]string{
		0: "MIGRATION_STATE_UNSPECIFIED",
		1: "MIGRATION_STATE_UNAPPLIED",
		2: "MIGRATION_STATE_CLEAN",
		3: "MIGRATION_STATE_DIRTY",
	}
	MigrationState_value = map[string]int32{
		"MIGRATION_STATE_UNSPECIFIED": 0,
		"MIGRATION_STATE_UNAPPLIED":   1,
		"MIGRATION_STATE_CLEAN":       2,
		"MIGRATION_STATE_DIRTY":       3,
	}
)

func (x MigrationState) Enum() *MigrationState {
	p := new(MigrationState)
	*p = x
	return p
}

func (x MigrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_migrieren_v1_service_proto_enumTypes[0].Descriptor()
}

func (MigrationState) Type() protoreflect.EnumType {
	return &file_migrieren_v1_service_proto_enumTypes[0]
}

func (x MigrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationState.Descriptor instead.
func (MigrationState) EnumDescriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{0}
}

// Migration reports the database, migration version, and bounded migrate logs.
type Migration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the configured logical database name requested by the caller.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// version is the target migration version for Migrate responses, or the
	// resulting migration version for ApplyMigrations responses.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// logs contains in-memory migrate log lines collected during execution.
	// The service caps this list at 100 entries and marks truncation with
	// "migration logs truncated" as the first entry.
	Logs          []string `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_migrieren_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Migration) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Migration) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Migration) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// MigrateRequest identifies a configured database and target schema version.
type MigrateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the configured logical database name, not a raw database URL.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// version is the target migration version. It must be greater than zero and
	// fit within the server-supported signed integer range.
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_migrieren_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *MigrateRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// MigrateResponse contains response metadata and the migration result.
type MigrateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains request metadata emitted by the service runtime.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// migration echoes the requested database/version and collected logs.
	Migration     *Migration `protobuf:"bytes,2,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_migrieren_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MigrateResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

// ApplyMigrationsRequest identifies a configured database to converge.
type ApplyMigrationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the configured logical database name, not a raw database URL.
	Database      string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationsRequest) Reset() {
	*x = ApplyMigrationsRequest{}
	mi := &file_migrieren_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationsRequest) ProtoMessage() {}

func (x *ApplyMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ApplyMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyMigrationsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// ApplyMigrationsResponse contains response metadata and the resulting
// migration state.
type ApplyMigrationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains request metadata emitted by the service runtime.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// migration reports the requested database, resulting version, and collected
	// logs.
	Migration     *Migration `protobuf:"bytes,2,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationsResponse) Reset() {
	*x = ApplyMigrationsResponse{}
	mi := &file_migrieren_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationsResponse) ProtoMessage() {}

func (x *ApplyMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ApplyMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyMigrationsResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ApplyMigrationsResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

// MigrationStatus reports the current version state for a configured database.
type MigrationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the configured logical database name requested by the caller.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// version is the current clean or dirty migration version.
	//
	// When state is MIGRATION_STATE_UNAPPLIED, version is zero and no migration
	// version has been recorded yet.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// state reports whether the migration version is unapplied, clean, or dirty.
	State         MigrationState `protobuf:"varint,3,opt,name=state,proto3,enum=migrieren.v1.MigrationState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStatus) Reset() {
	*x = MigrationStatus{}
	mi := &file_migrieren_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatus) ProtoMessage() {}

func (x *MigrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatus.ProtoReflect.Descriptor instead.
func (*MigrationStatus) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *MigrationStatus) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *MigrationStatus) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MigrationStatus) GetState() MigrationState {
	if x != nil {
		return x.State
	}
	return MigrationState_MIGRATION_STATE_UNSPECIFIED
}

// StatusRequest identifies the configured database to inspect.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the configured logical database name, not a raw database URL.
	Database      string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_migrieren_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// StatusResponse contains response metadata and current migration status.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains request metadata emitted by the service runtime.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// status reports the current migration version state.
	Status        *MigrationStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_migrieren_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StatusResponse) GetStatus() *MigrationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Database identifies one configured logical database.
type Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the configured logical database name accepted by migration RPCs.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_migrieren_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListDatabasesRequest requests the configured logical database names.
type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_migrieren_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{9}
}

// ListDatabasesResponse contains configured logical database names.
type ListDatabasesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains request metadata emitted by the service runtime.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// databases contains configured logical database names in config order.
	Databases     []*Database `protobuf:"bytes,2,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_migrieren_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrieren_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_migrieren_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatabasesResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListDatabasesResponse) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

var File_migrieren_v1_service_proto protoreflect.FileDescriptor

const file_migrieren_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1amigrieren/v1/service.proto\x12\fmigrieren.v1\"U\n" +
	"\tMigration\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04logs\x18\x03 \x03(\tR\x04logs\"F\n" +
	"\x0eMigrateRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xbe\x01\n" +
	"\x0fMigrateResponse\x12;\n" +
	"\x04meta\x18\x01 \x03(\v2'.migrieren.v1.MigrateResponse.MetaEntryR\x04meta\x125\n" +
	"\tmigration\x18\x02 \x01(\v2\x17.migrieren.v1.MigrationR\tmigration\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x16ApplyMigrationsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"\xce\x01\n" +
	"\x17ApplyMigrationsResponse\x12C\n" +
	"\x04meta\x18\x01 \x03(\v2/.migrieren.v1.ApplyMigrationsResponse.MetaEntryR\x04meta\x125\n" +
	"\tmigration\x18\x02 \x01(\v2\x17.migrieren.v1.MigrationR\tmigration\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x0fMigrationStatus\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.migrieren.v1.MigrationStateR\x05state\"+\n" +
	"\rStatusRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"\xbc\x01\n" +
	"\x0eStatusResponse\x12:\n" +
	"\x04meta\x18\x01 \x03(\v2&.migrieren.v1.StatusResponse.MetaEntryR\x04meta\x125\n" +
	"\x06status\x18\x02 \x01(\v2\x1d.migrieren.v1.MigrationStatusR\x06status\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14ListDatabasesRequest\"\xc9\x01\n" +
	"\x15ListDatabasesResponse\x12A\n" +
	"\x04meta\x18\x01 \x03(\v2-.migrieren.v1.ListDatabasesResponse.MetaEntryR\x04meta\x124\n" +
	"\tdatabases\x18\x02 \x03(\v2\x16.migrieren.v1.DatabaseR\tdatabases\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x86\x01\n" +
	"\x0eMigrationState\x12\x1f\n" +
	"\x1bMIGRATION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MIGRATION_STATE_UNAPPLIED\x10\x01\x12\x19\n" +
	"\x15MIGRATION_STATE_CLEAN\x10\x02\x12\x19\n" +
	"\x15MIGRATION_STATE_DIRTY\x10\x032\xd8\x02\n" +
	"\aService\x12H\n" +
	"\aMigrate\x12\x1c.migrieren.v1.MigrateRequest\x1a\x1d.migrieren.v1.MigrateResponse\"\x00\x12`\n" +
	"\x0fApplyMigrations\x12$.migrieren.v1.ApplyMigrationsRequest\x1a%.migrieren.v1.ApplyMigrationsResponse\"\x00\x12E\n" +
	"\x06Status\x12\x1b.migrieren.v1.StatusRequest\x1a\x1c.migrieren.v1.StatusResponse\"\x00\x12Z\n" +
	"\rListDatabases\x12\".migrieren.v1.ListDatabasesRequest\x1a#.migrieren.v1.ListDatabasesResponse\"\x00BEZ3github.com/alexfalkowski/migrieren/api/migrieren/v1\xea\x02\rMigrieren::V1b\x06proto3"

var (
	file_migrieren_v1_service_proto_rawDescOnce sync.Once
	file_migrieren_v1_service_proto_rawDescData []byte
)

func file_migrieren_v1_service_proto_rawDescGZIP() []byte {
	file_migrieren_v1_service_proto_rawDescOnce.Do(func() {
		file_migrieren_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migrieren_v1_service_proto_rawDesc), len(file_migrieren_v1_service_proto_rawDesc)))
	})
	return file_migrieren_v1_service_proto_rawDescData
}

var file_migrieren_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_migrieren_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_migrieren_v1_service_proto_goTypes = []any{
	(MigrationState)(0),             // 0: migrieren.v1.MigrationState
	(*Migration)(nil),               // 1: migrieren.v1.Migration
	(*MigrateRequest)(nil),          // 2: migrieren.v1.MigrateRequest
	(*MigrateResponse)(nil),         // 3: migrieren.v1.MigrateResponse
	(*ApplyMigrationsRequest)(nil),  // 4: migrieren.v1.ApplyMigrationsRequest
	(*ApplyMigrationsResponse)(nil), // 5: migrieren.v1.ApplyMigrationsResponse
	(*MigrationStatus)(nil),         // 6: migrieren.v1.MigrationStatus
	(*StatusRequest)(nil),           // 7: migrieren.v1.StatusRequest
	(*StatusResponse)(nil),          // 8: migrieren.v1.StatusResponse
	(*Database)(nil),                // 9: migrieren.v1.Database
	(*ListDatabasesRequest)(nil),    // 10: migrieren.v1.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),   // 11: migrieren.v1.ListDatabasesResponse
	nil,                             // 12: migrieren.v1.MigrateResponse.MetaEntry
	nil,                             // 13: migrieren.v1.ApplyMigrationsResponse.MetaEntry
	nil,                             // 14: migrieren.v1.StatusResponse.MetaEntry
	nil,                             // 15: migrieren.v1.ListDatabasesResponse.MetaEntry
}
var file_migrieren_v1_service_proto_depIdxs = []int32{
	12, // 0: migrieren.v1.MigrateResponse.meta:type_name -> migrieren.v1.MigrateResponse.MetaEntry
	1,  // 1: migrieren.v1.MigrateResponse.migration:type_name -> migrieren.v1.Migration
	13, // 2: migrieren.v1.ApplyMigrationsResponse.meta:type_name -> migrieren.v1.ApplyMigrationsResponse.MetaEntry
	1,  // 3: migrieren.v1.ApplyMigrationsResponse.migration:type_name -> migrieren.v1.Migration
	0,  // 4: migrieren.v1.MigrationStatus.state:type_name -> migrieren.v1.MigrationState
	14, // 5: migrieren.v1.StatusResponse.meta:type_name -> migrieren.v1.StatusResponse.MetaEntry
	6,  // 6: migrieren.v1.StatusResponse.status:type_name -> migrieren.v1.MigrationStatus
	15, // 7: migrieren.v1.ListDatabasesResponse.meta:type_name -> migrieren.v1.ListDatabasesResponse.MetaEntry
	9,  // 8: migrieren.v1.ListDatabasesResponse.databases:type_name -> migrieren.v1.Database
	2,  // 9: migrieren.v1.Service.Migrate:input_type -> migrieren.v1.MigrateRequest
	4,  // 10: migrieren.v1.Service.ApplyMigrations:input_type -> migrieren.v1.ApplyMigrationsRequest
	7,  // 11: migrieren.v1.Service.Status:input_type -> migrieren.v1.StatusRequest
	10, // 12: migrieren.v1.Service.ListDatabases:input_type -> migrieren.v1.ListDatabasesRequest
	3,  // 13: migrieren.v1.Service.Migrate:output_type -> migrieren.v1.MigrateResponse
	5,  // 14: migrieren.v1.Service.ApplyMigrations:output_type -> migrieren.v1.ApplyMigrationsResponse
	8,  // 15: migrieren.v1.Service.Status:output_type -> migrieren.v1.StatusResponse
	11, // 16: migrieren.v1.Service.ListDatabases:output_type -> migrieren.v1.ListDatabasesResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_migrieren_v1_service_proto_init() }
func file_migrieren_v1_service_proto_init() {
	if File_migrieren_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migrieren_v1_service_proto_rawDesc), len(file_migrieren_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migrieren_v1_service_proto_goTypes,
		DependencyIndexes: file_migrieren_v1_service_proto_depIdxs,
		EnumInfos:         file_migrieren_v1_service_proto_enumTypes,
		MessageInfos:      file_migrieren_v1_service_proto_msgTypes,
	}.Build()
	File_migrieren_v1_service_proto = out.File
	file_migrieren_v1_service_proto_goTypes = nil
	file_migrieren_v1_service_proto_depIdxs = nil
}
