// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: migrieren/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_Migrate_FullMethodName         = "/migrieren.v1.Service/Migrate"
	Service_ApplyMigrations_FullMethodName = "/migrieren.v1.Service/ApplyMigrations"
	Service_Status_FullMethodName          = "/migrieren.v1.Service/Status"
	Service_ListDatabases_FullMethodName   = "/migrieren.v1.Service/ListDatabases"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service runs configured database migrations.
type ServiceClient interface {
	// Migrate migrates a configured database to the requested version.
	//
	// Errors use InvalidArgument for versions outside the supported range,
	// NotFound for unknown databases, Canceled/DeadlineExceeded for stopped
	// requests, and Internal for configuration, source, database, or migration
	// failures.
	//
	// gRPC failures after request validation include trailers when the request
	// reaches the transport migrator. This includes unknown database names and
	// source/URL resolution failures; pre-migration validation InvalidArgument
	// responses do not use this trailer path.
	//   - migration-error: not_found, canceled, deadline_exceeded, invalid_config,
	//     invalid_migration, or unknown.
	//   - migration-log-count: the number of migration log lines returned.
	//   - migration-stage: source or url when configuration resolution failed.
	//   - migration-log-last: the last migration log line when logs were captured.
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	// ApplyMigrations applies all pending up migrations for a configured
	// database.
	//
	// If the database is already current, the request succeeds as a no-op and
	// reports the current migration version.
	//
	// Errors use NotFound for unknown databases, Canceled/DeadlineExceeded for
	// stopped requests, and Internal for configuration, source, database, final
	// version inspection, or migration failures.
	//
	// As with Migrate and Status, strict request cancellation depends on upstream
	// migrate v4 context support, which is currently incomplete in some database
	// driver paths.
	ApplyMigrations(ctx context.Context, in *ApplyMigrationsRequest, opts ...grpc.CallOption) (*ApplyMigrationsResponse, error)
	// Status reports the current migration version state for a configured
	// database.
	//
	// Errors use NotFound for unknown databases and Internal for configuration or
	// database inspection failures.
	//
	// Status does not apply migration files, but strict request cancellation
	// depends on upstream migrate v4 context support, which is currently
	// incomplete in some database driver inspection paths.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ListDatabases reports configured logical database names.
	//
	// This does not expose configured source strings, database URL strings, or
	// resolved secret values.
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, Service_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ApplyMigrations(ctx context.Context, in *ApplyMigrationsRequest, opts ...grpc.CallOption) (*ApplyMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyMigrationsResponse)
	err := c.cc.Invoke(ctx, Service_ApplyMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Service_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, Service_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
//
// Service runs configured database migrations.
type ServiceServer interface {
	// Migrate migrates a configured database to the requested version.
	//
	// Errors use InvalidArgument for versions outside the supported range,
	// NotFound for unknown databases, Canceled/DeadlineExceeded for stopped
	// requests, and Internal for configuration, source, database, or migration
	// failures.
	//
	// gRPC failures after request validation include trailers when the request
	// reaches the transport migrator. This includes unknown database names and
	// source/URL resolution failures; pre-migration validation InvalidArgument
	// responses do not use this trailer path.
	//   - migration-error: not_found, canceled, deadline_exceeded, invalid_config,
	//     invalid_migration, or unknown.
	//   - migration-log-count: the number of migration log lines returned.
	//   - migration-stage: source or url when configuration resolution failed.
	//   - migration-log-last: the last migration log line when logs were captured.
	Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	// ApplyMigrations applies all pending up migrations for a configured
	// database.
	//
	// If the database is already current, the request succeeds as a no-op and
	// reports the current migration version.
	//
	// Errors use NotFound for unknown databases, Canceled/DeadlineExceeded for
	// stopped requests, and Internal for configuration, source, database, final
	// version inspection, or migration failures.
	//
	// As with Migrate and Status, strict request cancellation depends on upstream
	// migrate v4 context support, which is currently incomplete in some database
	// driver paths.
	ApplyMigrations(context.Context, *ApplyMigrationsRequest) (*ApplyMigrationsResponse, error)
	// Status reports the current migration version state for a configured
	// database.
	//
	// Errors use NotFound for unknown databases and Internal for configuration or
	// database inspection failures.
	//
	// Status does not apply migration files, but strict request cancellation
	// depends on upstream migrate v4 context support, which is currently
	// incomplete in some database driver inspection paths.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// ListDatabases reports configured logical database names.
	//
	// This does not expose configured source strings, database URL strings, or
	// resolved secret values.
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedServiceServer) ApplyMigrations(context.Context, *ApplyMigrationsRequest) (*ApplyMigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyMigrations not implemented")
}
func (UnimplementedServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ApplyMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ApplyMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ApplyMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ApplyMigrations(ctx, req.(*ApplyMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrieren.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _Service_Migrate_Handler,
		},
		{
			MethodName: "ApplyMigrations",
			Handler:    _Service_ApplyMigrations_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Service_Status_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _Service_ListDatabases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migrieren/v1/service.proto",
}
