version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - bodyclose
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - ireturn
    - noinlineerr
    - paralleltest
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    lll:
      line-length: 140
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb*
      - third_party$
      - builtin$
      - examples$
