version: 2.1

jobs:
  build-service:
    docker:
      - image: alexfalkowski/go:1.4
      - image: postgres:16-bullseye
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
      - image: grafana/mimir:latest
        command: -server.http-listen-port=9009 -auth.multitenancy-enabled=false -ingester.ring.replication-factor=1
    working_directory: ~/migrieren
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: dockerize -wait tcp://localhost:5432 -wait tcp://localhost:9009 -timeout 1m
      - restore_cache:
          name: restore go deps
          keys:
            - migrieren-go-cache-{{ checksum "go.sum" }}
            - migrieren-go-cache-
      - restore_cache:
          name: restore ruby deps
          keys:
            - migrieren-ruby-cache-{{ checksum "test/Gemfile.lock" }}
            - migrieren-ruby-cache-
      - run: make dep
      - save_cache:
          name: save go deps
          key: migrieren-go-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - save_cache:
          name: save ruby deps
          key: migrieren-ruby-cache-{{ checksum "test/Gemfile.lock" }}
          paths:
            - test/vendor
      - restore_cache:
          name: restore go build cache
          keys:
            - migrieren-go-build-cache-{{ checksum "go.sum" }}
            - migrieren-go-build-cache-
      - run: make lint
      - run: make proto-breaking
      - run: make sec
      - run: make features
      - run: make build analyse
      - save_cache:
          name: save go build cache
          key: migrieren-go-build-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.cache/go-build
      - run: make coverage
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: large
  build-docker:
    docker:
      - image: alexfalkowski/go:1.4
    working_directory: ~/migrieren
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build-docker
      - run: make trivy
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.4
    working_directory: ~/migrieren
    steps:
      - checkout
      - run: release
    resource_class: large
  push-docker:
    docker:
      - image: alexfalkowski/go:1.4
    working_directory: ~/migrieren
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make push-docker
    resource_class: large

workflows:
  migrieren:
    jobs:
      - build-service
      - build-docker:
          context: gh
      - release:
          context: gh
          requires:
            - build-service
            - build-docker
          filters:
            branches:
              only: master
      - push-docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
