version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.19
      - image: postgres:latest
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: make dep
      - run: make lint
      - run: make sec
      - run: make features
      - run: make goveralls
      - store_artifacts:
          path: test/reports
  release:
    docker:
      - image: alexfalkowski/release:2.0
    steps:
      - checkout
      - run: release
  docker:
    docker:
      - image: alexfalkowski/go:1.19
    steps:
      - checkout
      - run: make assets
      - setup_remote_docker
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make docker

workflows:
  migrieren:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
      - docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
