# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: migrieren/v1/service.proto for package 'Migrieren.V1'

require 'grpc'
require 'migrieren/v1/service_pb'

module Migrieren
  module V1
    module Service
      # Service runs configured database migrations.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'migrieren.v1.Service'

        # Migrate migrates a configured database to the requested version.
        #
        # Errors use InvalidArgument for versions outside the supported range,
        # NotFound for unknown databases, Canceled/DeadlineExceeded for stopped
        # requests, and Internal for configuration, source, database, or migration
        # failures.
        #
        # gRPC failures after request validation include trailers when the request
        # reaches the transport migrator. This includes unknown database names and
        # source/URL resolution failures; pre-migration validation InvalidArgument
        # responses do not use this trailer path.
        # - migration-error: not_found, canceled, deadline_exceeded, invalid_config,
        #   invalid_migration, or unknown.
        # - migration-log-count: the number of migration log lines returned.
        # - migration-stage: source or url when configuration resolution failed.
        # - migration-log-last: the last migration log line when logs were captured.
        rpc :Migrate, ::Migrieren::V1::MigrateRequest, ::Migrieren::V1::MigrateResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
