# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: migrieren/v1/service.proto for package 'Migrieren.V1'

require 'grpc'
require 'migrieren/v1/service_pb'

module Migrieren
  module V1
    module Service
      # Service allows to migrate databases.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'migrieren.v1.Service'

        # Migrate a specific database to version.
        rpc :Migrate, ::Migrieren::V1::MigrateRequest, ::Migrieren::V1::MigrateResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
