# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: migrieren/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'


descriptor_data = "\n\x1amigrieren/v1/service.proto\x12\x0cmigrieren.v1\x1a\x1cgoogle/api/annotations.proto\"U\n\tMigration\x12\x1a\n\x08\x64\x61tabase\x18\x01 \x01(\tR\x08\x64\x61tabase\x12\x18\n\x07version\x18\x02 \x01(\x04R\x07version\x12\x12\n\x04logs\x18\x03 \x03(\tR\x04logs\"F\n\x0eMigrateRequest\x12\x1a\n\x08\x64\x61tabase\x18\x01 \x01(\tR\x08\x64\x61tabase\x12\x18\n\x07version\x18\x02 \x01(\x04R\x07version\"\xbe\x01\n\x0fMigrateResponse\x12;\n\x04meta\x18\x01 \x03(\x0b\x32\'.migrieren.v1.MigrateResponse.MetaEntryR\x04meta\x12\x35\n\tmigration\x18\x02 \x01(\x0b\x32\x17.migrieren.v1.MigrationR\tmigration\x1a\x37\n\tMetaEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x32{\n\x07Service\x12p\n\x07Migrate\x12\x1c.migrieren.v1.MigrateRequest\x1a\x1d.migrieren.v1.MigrateResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/migrate/{database}/{version}BEZ3github.com/alexfalkowski/migrieren/api/migrieren/v1\xea\x02\rMigrieren::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Migrieren
  module V1
    Migration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("migrieren.v1.Migration").msgclass
    MigrateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("migrieren.v1.MigrateRequest").msgclass
    MigrateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("migrieren.v1.MigrateResponse").msgclass
  end
end
