# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: migrieren/v1/service.proto for package 'Migrieren.V1'

require 'grpc'
require 'migrieren/v1/service_pb'

module Migrieren
  module V1
    module Service
      # Service runs configured database migrations.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'migrieren.v1.Service'

        # Migrate migrates a configured database to the requested version.
        #
        # Errors use InvalidArgument for versions outside the supported range,
        # NotFound for unknown databases, Canceled/DeadlineExceeded for stopped
        # requests, and Internal for configuration, source, database, or migration
        # failures.
        #
        # gRPC failures after request validation include trailers when the request
        # reaches the transport migrator. This includes unknown database names and
        # source/URL resolution failures; pre-migration validation InvalidArgument
        # responses do not use this trailer path.
        # - migration-error: not_found, canceled, deadline_exceeded, invalid_config,
        #   invalid_migration, or unknown.
        # - migration-log-count: the number of migration log lines returned.
        # - migration-stage: source or url when configuration resolution failed.
        # - migration-log-last: the last migration log line when logs were captured.
        rpc :Migrate, ::Migrieren::V1::MigrateRequest, ::Migrieren::V1::MigrateResponse
        # ApplyMigrations applies all pending up migrations for a configured
        # database.
        #
        # If the database is already current, the request succeeds as a no-op and
        # reports the current migration version.
        #
        # Errors use NotFound for unknown databases, Canceled/DeadlineExceeded for
        # stopped requests, and Internal for configuration, source, database, final
        # version inspection, or migration failures.
        #
        # Failures after request routing expose the same safe diagnostic trailers as
        # Migrate, including migration-error, migration-log-count, migration-stage,
        # and migration-log-last when those values are available.
        #
        # As with Migrate and Status, strict request cancellation depends on upstream
        # migrate v4 context support, which is currently incomplete in some database
        # driver paths.
        rpc :ApplyMigrations, ::Migrieren::V1::ApplyMigrationsRequest, ::Migrieren::V1::ApplyMigrationsResponse
        # PlanMigrations reports current status and pending up migration versions for
        # a configured database without applying migration files.
        #
        # Errors use NotFound for unknown databases, Canceled/DeadlineExceeded for
        # stopped requests, and Internal for configuration, source, or database
        # inspection failures.
        #
        # Failures after request routing expose the same safe diagnostic trailers as
        # Migrate, including migration-error, migration-log-count, migration-stage,
        # and migration-log-last when those values are available.
        #
        # PlanMigrations opens the configured migration source to discover available
        # versions, but it does not read migration bodies or expose configured source
        # strings, database URL strings, or resolved secret values.
        rpc :PlanMigrations, ::Migrieren::V1::PlanMigrationsRequest, ::Migrieren::V1::PlanMigrationsResponse
        # Status reports the current migration version state for a configured
        # database.
        #
        # Errors use NotFound for unknown databases and Internal for configuration or
        # database inspection failures.
        #
        # Status does not apply migration files, but strict request cancellation
        # depends on upstream migrate v4 context support, which is currently
        # incomplete in some database driver inspection paths.
        rpc :Status, ::Migrieren::V1::StatusRequest, ::Migrieren::V1::StatusResponse
        # ListDatabases reports configured logical database names.
        #
        # This does not expose configured source strings, database URL strings, or
        # resolved secret values.
        rpc :ListDatabases, ::Migrieren::V1::ListDatabasesRequest, ::Migrieren::V1::ListDatabasesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
